---
title: "HW1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
y1<-c(3129, 3000, 2865, 2890)
y2<-c(3200, 3300, 2975, 3150)
y3<-c(2800, 2900, 2985, 2765)
y4<-c(2600, 2700, 2600, 2765)
y <- c(y1, y2, y3, y4)
n <- rep(4, 4) 
group <- rep(1:4, n)
group_df <- data.frame(y, group)
group_df <- transform(group_df, group = factor(group))
```


### Problem 1. (a)
```{r}
summary(aov(y ~ group, data = group_df))#MSE= 12380
```

### Problem 1. (b)
```{r}
lsd<-qt(p=.975, df=12)*sqrt(12380*2/4)
abs(mean(y1)-mean(y2))#185.25
abs(mean(y1)-mean(y3))#108.5
abs(mean(y1)-mean(y4))#304.75
abs(mean(y2)-mean(y3))#293.75
abs(mean(y2)-mean(y4))#490
abs(mean(y3)-mean(y4))#196.25
```

### Problem 1. (c)
```{r}
plot(lm(y ~ group),2)
```

### Problem 1. (d)
```{r}
plot(lm(y ~ group),1)
```

### Problem 2. 
```{r}
TukeyHSD(x=aov(y ~ group, data = group_df), conf.level=0.95)
```


```{r}
Z1<-c(100, 96, 92, 96, 92)
Z2<-c(76, 80, 75, 84, 82)
Z3<-c(108, 100, 96, 98, 100)
Z <- c(Z1, Z2, Z3)
nZ <- rep(5, 3) 
groupZ <- rep(1:3, nZ)
groupZ_df <- data.frame(Z, groupZ)
groupZ_df <- transform(groupZ_df, groupZ = factor(groupZ))
```

### Problem 3. (a) 
```{r}
summary(aov(Z ~ groupZ, data = groupZ_df))
```
### Problem 3. (b) 
```{r}
par(mfrow=c(1,2))
plot(lm(Z ~ groupZ, data = groupZ_df), which=1:2)#정규성 만족
bartlett.test(Z ~ groupZ, groupZ_df)#등분산성 만족
```

### Problem 3. (c) 
```{r}
summary(Z2)
n<-5
xbar<-mean(Z2)
s<-var(Z2)
margin <- qt(0.975,df=n-1)*s/sqrt(n)
xbar-margin
xbar+margin

TukeyHSD(aov(Z ~ groupZ, data = groupZ_df), conf.level = 0.99)
t.test(Z2, Z3, var.equal = TRUE, conf.level = 0.99)
```

### Problem 4. 
```{r}
library(car)
leveneTest(aov(Z ~ groupZ, data = groupZ_df), center=median)#등분산성 만족
```

